#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME :=

include $(IDF_PATH)/make/project.mk


cmake_minimum_required(VERSION 3.5)
include($ENV{IDF_PATH}\tools\cmake\project.cmake)
project(Main)

